spring:
  application:
    name: Api-Gateway
  config:
    import: optional:configserver:http://localhost:8080
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  main:
    web-application-type: reactive

server:
  port: 8081

