# Use root/example as user/password credentials
version: '3.1'
services:
  product-service-db:
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: product-microservice-db
      MYSQL_PASSWORD: root1
      MYSQL_ROOT_PASSWORD: root1
   
